### ISSUE TITLE
ERROR: pull access denied for oceanprotocol/provider-backend

### ISSUE THREAD

**Issue by VasiliyS** [oceanprotocol/docker-images#12]
running docker-compose results in:

ERROR: pull access denied for oceanprotocol/provider-backend, repository does not exist or may require 'docker login'

**Comment by eruizgar91** [comment]
Hi @VasiliyS . We miss to merge this PR #11 that fix this in master. It should be fixed now with the merge. Thank you :)

**Comment by VasiliyS** [comment]
Yes, everything works now. Congrats on the release!
