### ISSUE TITLE
Run docker images individually

### ISSUE THREAD

**Issue by eruizgar91** [oceanprotocol/docker-images#25]
## Expected Behavior
I would like to be able to run the different docker containers without needing to have running all of them in the docker-compose. 

## Current Behavior
Currently, beacuse of the dependencies between the different docker images, the docker-entrypoint is listening until the rest of the docker images are up and running. It would be great to have two different behaviours.

### Possible Solution

1- Pass a environment variable to specify if there is running in a docker-compose or not.
2- Wait for a while and if there are not more images start in the standalone mode.
3- Create two different entry points.

**Comment by jcortejoso** [comment]
With #71 images can be run individually using `start-ocean.sh` or directly with their compose files.
