### ISSUE TITLE
start_ocean.sh: home folder should be system agnostic

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docker-images#30]
I would assume startup script in combination with e.g. developing on pleuston would fail right now on all non-Unix systems, cause there's no `~/` in those systems, like Windows. Or is there when you have the unix subsystem installed? Completely out of touch with latest Windows developments :-) 

On pleuston I'm using the Node.js environment to detect that, like:

```js
const homeFolder = process.env.HOME || process.env.USERPROFILE
```

**Comment by jcortejoso** [comment]
For now `docker-images` is not compatible with Docker for Windows. If somebody needs us please open a new issue.
