### ISSUE TITLE
Keeper-Contracts fails if i specify kovan as network

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/docker-images#51]
I changed in `start_ocean.sh`
```
# Must be set to true for the first run, change it to "false" to avoid migrating the smart contracts on each run.
export DEPLOY_CONTRACTS="false"
# Specify which ethereum client to run or connect to: kovan, ganache, or ocean_poa_net_local
export KEEPER_NETWORK_NAME="kovan"
```

did `./start_ocean.sh --no-pleuston --latest`

this will lead to:
`/keeper-contracts/scripts/keeper.sh: line 7: parity: command not found`

inside the `keeper-contracts` docker instance.

**Comment by H34D** [comment]
touches https://github.com/oceanprotocol/keeper-contracts/issues/172

**Comment by theoturner** [comment]
Also facing this issue, would like to use docker-images with Kovan.

**Comment by jcortejoso** [comment]
With the latest changes you can run `docker-images` connected with Kovan network using the option `--local-kovan-node`. Example:
```bash 
bash ./start-ocean.sh --local-kovan-node
```
