### ISSUE TITLE
Hard-coded subnet addresses

### ISSUE THREAD

**Issue by theoturner** [oceanprotocol/docker-images#76]
docker-compose-local-parity-node.yml hard-codes subnet addresses in the 172.15 range, resulting in the following if this subnet is not set up:

```
ERROR: for [CONTAINER_X]  Cannot start service X: Invalid address 172.15.0.X: It does not belong to any of this network's subnets
```
for each component X

**Comment by H34D** [comment]
@theoturner try to remove all the ocean containers, volumes, images and networks and run `./start_ocean.sh --latest` again

**Comment by theoturner** [comment]
I still get the same error. It seems the subnet is not being created - can reproduce on both MacOS 10.14 and Ubuntu 18.04.

**Comment by theoturner** [comment]
A full reset of docker worked.
